function [B, valid_id] = CZ_SPL_est(X,Y,x,y,TRI,v1,v2,v3,nt,nc,nv,d)
% This function takes a list of location (X, Y) and TRI info as inputs
% The output contains values of associated Bernstein basis polynomials of degree d relative to the TRI

% Arguments
% (X, Y): the location of points on a 2-d space
% (x,y,TRI,v1,v2,v3,nt,nc,nv,d): these are associated values of
% Triangulation TRI. (v1,v2,v3,nt,nc,nv,d)are generated by calling
% trilist()

[tnum,b]=tsearchn([x,y],TRI,[X,Y]);
n_x=length(X);

valid_id = 1:n_x;
B=zeros(n_x,nc);
for i=1:n_x
    j=tnum(i);
    if( ~isnan(j))
        B(i,[v1(j),v2(j),v3(j)])=basis(d,b(i,1),b(i,2),b(i,3));
    else
        valid_id = setdiff(valid_id, i);
    end
  
end

end